title: Al Khizanah
subtitle: A group of people gathered to make software

url: "https://alkhizanah.github.io"
baseurl: ""

organization_github: https://github.com/alkhizanah

markdown: kramdown
highlighter: rouge

sass:
  style: expanded
  sourcemap: development

permalink: /posts/:title/

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: docs
    values:
      layout: doc

exclude:
  - README.md
  - vendor/
